name: Build Snapshot Cherry

on:
  push:
    branches:
      - sub

permissions:
  contents: write

jobs:
  build-snapshot:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Install GCC (MinGW)
      run: |
        choco install mingw -y
        echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

    - name: Build executable
      run: |
        pyinstaller --onefile cherry.py
        move /Y dist\* .
        rd /S /Q dist

    - name: Create snapshot pre-release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: snapshot-${{ github.run_number }}
        name: "Snapshot Build ${{ github.run_number }}"
        files: cherry.exe
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
