name: CherryBlossomTest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-compiler:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

       - name: Install Python dependencies
        run: |
          pip install colorama

      - name: Install MinGW (for g++)
        run: |
          choco install mingw -y
          refreshenv
          g++ --version

      - name: Run compiler (generate C++ code)
        run: |
          python cherry.py test/test.cb
